image: $CI_REGISTRY/qqvp/containers/qqvp-dev:latest

# TODO
# - Cache builds to avoid re-building same commit

###################################################################
#    Configs
###################################################################

variables:
  COMMON_CONFIG_OPTS: --enable-lto --disable-capstone --disable-guest-agent --enable-plugins --assert-target-compiler
  HEX_CONFIG_OPTS: --disable-fdt --disable-tools --disable-slirp --disable-sdl --disable-vnc --disable-gtk --disable-blobs
  AARCH64_CONFIG_OPTS: --enable-fdt --enable-slirp --disable-debug-info --disable-debug-tcg --enable-virtfs --enable-avx2 --enable-avx512f --disable-png --disable-sanitizers

  GENERIC_CONFIG_CMD: installdir="$(realpath "$(mktemp -d -p .)")" && ../configure --prefix="$$installdir" $COMMON_CONFIG_OPTS
  HEX_CONFIG_CMD: $GENERIC_CONFIG_CMD $HEX_CONFIG_OPTS --target-list=hexagon-softmmu,hexagon-linux-user
  AARCH64_CONFIG_CMD: $GENERIC_CONFIG_CMD $AARCH64_CONFIG_OPTS --target-list=aarch64-softmmu,aarch64-linux-user

  QQVP_PROJECT_URL: gitlab.qualcomm.com/qqvp

###################################################################
#    Base templates
###################################################################

.base-build:
  variables: {BUILDDIR: $CI_JOB_NAME}
  script:
    mkdir $BUILDDIR &&
    cd $BUILDDIR &&
    echo "Configuring with '$CONFIG_CMD'" &&
    eval $CONFIG_CMD &&
    make -j
  artifacts:
    paths: [ $BUILDDIR ]

.base-install:
  script:
    builddir="$(echo $CI_JOB_NAME | cut -d_ -f1)_build" &&
    cd $builddir &&
    make install

.base-check-tcg:
  script:
    builddir="$(echo $CI_JOB_NAME | cut -d_ -f1)_build" &&
    cd $builddir &&
    make check-tcg V=1 LSAN_OPTIONS=detect_leaks=0

.base-check:
  script:
    builddir="$(echo $CI_JOB_NAME | cut -d_ -f1)_build" &&
    cd $builddir &&
    make check

###################################################################
#    Jobs
###################################################################

# NEEDSWORK: this job assumes all MRs will be against "master". This was done
# because working with $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME is tricky.
checkpatch:
  variables:
    REMOTE_URL: https://gitlab-ci-token:${CI_JOB_TOKEN}@${QQVP_PROJECT_URL}/qemu/qemu.git
  allow_failure: true
  # Note: we try set-url first because gitlab runners will preserve the repo
  # configs in between builds, so `remote add` would fail.
  script:
    git remote set-url mainrepo $REMOTE_URL >/dev/null 2>&1 || git remote add mainrepo $REMOTE_URL &&
    git fetch mainrepo master &&
    if test -n "$(git rev-list FETCH_HEAD..HEAD)";
    then
      ./scripts/checkpatch.pl --no-signoff --branch FETCH_HEAD..HEAD;
    fi

hexagon_build:
  extends: .base-build
  variables: { CONFIG_CMD: $HEX_CONFIG_CMD }
hexagon_install:
  needs: [hexagon_build]
  extends: .base-install
hexagon_check-tcg:
  needs: [hexagon_build]
  extends: .base-check-tcg
hexagon_check:
  needs: [hexagon_build]
  extends: .base-check

san-hexagon_build:
  extends: .base-build
  variables: { CONFIG_CMD: "$HEX_CONFIG_CMD --enable-sanitizers" }
san-hexagon_install:
  needs: [san-hexagon_build]
  extends: .base-install
san-hexagon_check-tcg:
  needs: [san-hexagon_build]
  extends: .base-check-tcg
san-hexagon_check:
  needs: [san-hexagon_build]
  extends: .base-check

aarch64_build:
  extends: .base-build
  variables: { CONFIG_CMD: $AARCH64_CONFIG_CMD }
aarch64_install:
  needs: [aarch64_build]
  extends: .base-install
aarch64_check-tcg:
  needs: [aarch64_build]
  extends: .base-check-tcg
aarch64_check:
  needs: [aarch64_build]
  extends: .base-check

test_hexagon_perf:
  needs: [hexagon_build]
  tags:
    - performance-hardware
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${QQVP_PROJECT_URL}/qemu/qemu-hexagon-perf.git
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${QQVP_PROJECT_URL}/qemu/qemu-hexagon-benchmarks.git
    - mkdir perf_results
    - ./qemu-hexagon-perf/customer_test_suite.py
        --bench-dir ./qemu-hexagon-benchmarks/
        --qemu-user-bin-dir ${PWD}/hexagon_build/ --qemu-bin-dir ${PWD}/hexagon_build/
        --output-file ./perf-results.json
        --inspector perf-stat
  artifacts:
    paths: [ "perf-results.json" ]
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"

