{
    'hexnn': {
        'qemu-program': 'qemu-hexagon',
        'test-dir': 'nn/hexagon-nn/',
        'test-program': 'unit_test',
        'prog-args': [],
        'qemu-args': [],
        'check': None,
    },
    'h2-mobilenet-v1-quant': {
        'qemu-program': 'qemu-system-hexagon',
        'test-dir': 'nn/hexagon-nn/h2/',
        'test-program': 'booter',
        'prog-args': [],
        'qemu-args': ['-M', 'V68_H2', '-append',
                './pickle_driver.elf --pickle_in ./mobilenet_v1_quant.pickle --perf 0 '
                '--warmup_run 1 --in ./mobilenet_v1_quant.0.dat --out ./mobilenet_v1_quant.out',
            '-cpu', 'any,sched-limit=on',
            ],
        'check': ['sha256sum', '--status', '--check', 'ref.sha256',],
    },
    'snpe-m10': {
        'qemu-program': 'qemu-system-hexagon',
        'test-dir': 'nn/snpe/m10/',
        'test-program': 'runelf.pbn',
        'prog-args': [],
        'qemu-args': ['-M', 'V68N_1024', '-append',
            './run_main_on_hexagon_sim -- SnpeDspEmulatorDriver_q.so --inputDataPath ./inputs',
            '-cpu', 'any,usefs={test_dir},sched-limit=on', ],
        'check': None,
    },
    'mp3decoder': {
        'qemu-program': 'qemu-hexagon',
        'test-dir': 'apps/mp3decoder/',
        'test-program': 'main',
        'prog-args': ['./Hikobe_Manor.mp3', './Hikobe_Manor.pcm', './run.log',],
        'qemu-args': [],
        'check': ['sha1sum', '--check', './Hikobe_Manor.sha',],
    },
    'gzip': {
        'qemu-program': 'qemu-system-hexagon',
        'test-dir': 'apps/gzip',
        'test-program': 'gzip',
        'prog-args': [],
        'qemu-args': [],
        'check': ['sha256sum', '--status', '--check', 'ref.sha256',],
    },
    'H2-linux': {
        'qemu-program': 'qemu-system-hexagon',
        'test-dir': 'OS/h2_linux/',
        'test-program': 'loadlinux.v68',
        'prog-args': [],
        'qemu-args': ['-M', 'V66_Linux', '-cpu', 'any,sched-limit=on',],
        'check': None,
    },
    'mbfw': {
        'qemu-program': 'qemu-system-hexagon',
        'test-dir': 'microbench/mbfw_bench/',
        'test-program': None,
        'test-program-list': [
                'hvx_relu_minmax_fp_2blk_1T_TM01.elf',
                'hvx_memcpy_vtcm_to_vtcm_sync_non_allwait_mode_1T_TM01.elf',
                'hvx_conv3x3_v68_1T_TM01.elf',
                'hvx_bilateral_v68_1T_TM01.elf',
                'hvx_bandwidth_gatherh_1T_TM01.elf',
                'hvx_bandwidth_scatterh_1T_TM01.elf',
                'HVX_interlock_vtc_short0_1T_TM01.elf',
                'HVX_packet_rate_1T_TM01.elf',
                'DMA_bw_vtcm_to_l2_hit_1T_TM01.elf',
                ],
        'prog-args': [],
        'qemu-args': [],
        'check': None,
    },
    'mbfw-coproc': {
        'qemu-program': 'qemu-system-hexagon',
        'test-dir': 'microbench/mbfw_bench/',
        'test-program': None,
        'test-program-list': [
                'hmx_conv3x3_u8xs8_act_random_wgt_random_1T_TM01.elf',
                'hmx_conv3x3_cvt_u16xs8_act_random_wgt_random_1T_TM01.elf',
                'HMX_mpy_u8xs8_acc_interlock_d128_TM01.elf',
                'HMX_bias_store2_rate_1T_TM01.elf',
                'HMX_bias_load2_rate_1T_TM01.elf',
                'hmx_matmult_cvt_u8xs8_hvx_convdw_v68_dma_4T_TM0F.elf',
                'hmx_matmult_hfxhf_act_random_wgt_random_1T_TM01.elf',
                ],
        'prog-args': [],
        'qemu-args': ['-M', 'virt_coproc', '-cpu', 'any,sched-limit=on',],
        'check': None,
    },
    "libcxx-alg_sorting": {
        "qemu-program": "qemu-system-hexagon",
        "test-dir": "apps/libcxx_test",
        "test-program": "../QuRT_SDK/sdkv75/runelf.pbn",
        "prog-args": [
            "-append",
            "../QuRT_SDK/sdkv75/run_main_on_hexagon_sim -- ./alg.sorting.complexity.exe",
        ],
        "qemu-args": ["-cpu", "any,usefs=../QuRT_SDK/sdkv75/"],
        "check": None,
    },
    "libcxx-regex_exponential": {
        "qemu-program": "qemu-system-hexagon",
        "test-dir": "apps/libcxx_test",
        "test-program": "../QuRT_SDK/sdkv75/runelf.pbn",
        "prog-args": [
            "-append",
            "../QuRT_SDK/sdkv75/run_main_on_hexagon_sim -- ./regex_exponential.exe",
        ],
        "qemu-args": ["-cpu", "any,usefs=../QuRT_SDK/sdkv75/"],
        "check": None,
    },
    "libcxx-next_prime": {
        "qemu-program": "qemu-system-hexagon",
        "test-dir": "apps/libcxx_test",
        "test-program": "../QuRT_SDK/sdkv75/runelf.pbn",
        "prog-args": [
            "-append",
            "../QuRT_SDK/sdkv75/run_main_on_hexagon_sim -- ./next_prime.exe",
        ],
        "qemu-args": ["-cpu", "any,usefs=../QuRT_SDK/sdkv75/"],
        "check": None,
    },
    "h264-butterfly": {
        "qemu-program": "qemu-system-hexagon",
        "test-dir": "apps/h264",
        "test-program": "h264",
        "prog-args": [
            "-append",
            "-b 4 8 -t 2 -in ./Butterfly_30_qvga.264 "
            "-o ./Butterfly_30_qvga.yuv -s appstats.txt",
        ],
        "qemu-args": [],
        "check": [
            "sha256sum",
            "--status",
            "--check",
            "ref.sha256",
        ],
    },
    'dav1d-480p-240p-160p': {
        'qemu-program': 'qemu-hexagon',
        'test-dir': 'apps/dav1d/',
        'test-program': './bin/dav1d',
        'needs-ld-prefix': True,
        'prog-args': ['-q', '--threads', '1', '-i', './share/autostitch-480p-240p-160p.ivf', '--limit=300', '--verify', 'e2550fe403e83cae20d1abe044a87cae',],
        'qemu-args': [],
        'check': None,
    },
    'coremark': {
        'qemu-program': 'qemu-system-hexagon',
        'test-dir': 'apps/coremark',
        'test-program': 'coremark.exe',
        'prog-args': [],
        'qemu-args': [],
        'check': None,
    },
}
