{
    'mp3decoder': {
        'qemu-program': 'qemu-hexagon',
        'test-dir': 'apps/mp3decoder/',
        'test-program': 'main',
        'prog-args': ['./test_48khz_s.mp3', './output.pcm', './run.log',],
        'qemu-args': [],
        'check': ['cmp', './output.pcm', './run.stdout.golden',],
    },
    'mbfw': {
        'qemu-program': 'qemu-system-hexagon',
        'test-dir': 'microbench/mbfw_bench/',
        'test-program': None,
        'test-program-list': [
                'hvx_relu_minmax_fp_2blk_1T_TM01.elf',
                ],
        'prog-args': [],
        'qemu-args': [],
        'check': None,
    },
    'snpe-m10': {
        'qemu-program': 'qemu-system-hexagon',
        'test-dir': 'nn/snpe/m10/',
        'test-program': 'runelf.pbn',
        'prog-args': [],
        'qemu-args': ['-M', 'V68N_1024', '-append',
            './run_main_on_hexagon_sim -- SnpeDspEmulatorDriver_q.so --inputDataPath ./inputs',
            '-cpu', 'any,usefs={test_dir},sched-limit=on', ],
        'check': None,
    },
    'gzip': {
        'qemu-program': 'qemu-system-hexagon',
        'test-dir': 'apps/gzip',
        'test-program': 'gzip',
        'prog-args': [],
        'qemu-args': [],
        'check': ['sha256sum', '--status', '--check', 'ref.sha256',],
    },
    'h2-mobilenet-v1-quant': {
        'qemu-program': 'qemu-system-hexagon',
        'test-dir': 'nn/hexagon-nn/h2/',
        'test-program': 'booter',
        'prog-args': [],
        'qemu-args': ['-M', 'V68_H2', '-append',
                './pickle_driver.elf --pickle_in ./mobilenet_v1_quant.pickle --perf 0 '
                '--warmup_run 1 --in ./mobilenet_v1_quant.0.dat --out ./mobilenet_v1_quant.out',
            '-cpu', 'any,sched-limit=on',
            ],
        'check': ['sha256sum', '--status', '--check', 'ref.sha256',],
    },
    'coremark': {
        'qemu-program': 'qemu-system-hexagon',
        'test-dir': 'apps/coremark',
        'test-program': 'coremark.exe',
        'prog-args': [],
        'qemu-args': [],
        'check': None,
    },
}
