/*
 * Hexagon Baseboard System emulation.
 *
 * Copyright (c) 2020-2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <http://www.gnu.org/licenses/>.
 */

#include "machine_cfg_v66g_1024.h.inc"
#include "machine_cfg_v69na_1024.h.inc"
#include "machine_cfg_v73m.h.inc"
#include "machine_cfg_v73na_1024.h.inc"
#include "machine_cfg_v75na_1024.h.inc"
#include "machine_cfg_v79na_1.h.inc"
#include "machine_cfg_v79m_1.h.inc"
#include "machine_cfg_v81qa_1.h.inc"
#include "machine_cfg_v81na_2.h.inc"
#include "machine_cfg_v81dgb_1.h.inc"
#include "machine_cfg_sa8540p_cdsp0.h.inc"
#include "machine_cfg_sa8775_cdsp0.h.inc"
#include "machine_cfg_v68n_1024.h.inc"

#include "machine_cfg_sa8797p_nsp0.h.inc"
#include "machine_cfg_sc8480xp_nsp0.h.inc"
